### ISSUE TITLE
Data location tag not deleted

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#1121]
@swelborn 

Sometimes the tag indicating raw data is available on mothership6 is not deleted during a streaming session.
![image](https://github.com/OpenChemistry/distiller/assets/15657108/40bd5e9f-55f5-4210-b687-a9244dac4297)

This is intermittent. Sometimes the tag is removed and sometimes not.

**Comment by swelborn** [comment]
@ercius i forgot if you told me, but is the json file still on MS6 for these particular acquisitions?

**Comment by ercius** [comment]
Sorry I missed this. I did not check for the JSON files. Ill try to check today to see if I can figure it out. Or this will have to wait until our next streaming session.

**Comment by swelborn** [comment]
sounds good 👍

**Comment by ercius** [comment]
Please check scan ids 17044 - 17061. These show the issue I think. JSON is on mothership6 even though the data was streamed.

**Comment by swelborn** [comment]
This should be fixed with latest changes. Closing for now. If it shows up again, just reopen.
