### ISSUE TITLE
change data delete behavior

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#171]
deleting data works except that we want to be able to do two operations:
1. Delete the scan data (called raw data) on MS6 to allow for more scans to be acquired
2. Delete a scan from Distiller

I should be able to do both of these or only 1 of these. Currently, you can do (2) or (1 and 2). I would also like to be able to do 1 only and keep the metadata in Distiller.

**Comment by cjh1** [comment]
@ercius You can do just 1. ( or may be I missing what you want to be able todo! ). If you click on the x on the location chip it will just remove the files from MS6, see image below:

![screen](https://user-images.githubusercontent.com/1031053/148229037-51c4ab34-f316-49aa-9b37-54b0e2be8bb2.png)
