### ISSUE TITLE
Add distiller id to scan page

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#277]

**Comment by cjh1** [comment]
@ercius Is this what you mean? We already have your "scan id" on the scan page.

**Comment by ercius** [comment]
Yes. It would be good to see both IDs on that page

**Comment by cjh1** [comment]
@ercius I think it would be good come up with consistent names for these two ids, what about:

scan id generated by detector => Detector Scan ID
scan id generated by distiller => Distiller Scan ID

I am open to suggestions?

**Comment by ercius** [comment]
@cjh1 I think that makes sense. Lets go with those!

**Comment by cjh1** [comment]
Fixed in #313, deployed.
