### ISSUE TITLE
Remove threshold included in filename

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#281]
When  #280 is done.

**Comment by cjh1** [comment]
@ercius Was about to do this but wanted to check with you if you ever count a scan with two different thresholds? If we remove the threshold from the filename two counts with different thresholds would override each other.

**Comment by ercius** [comment]
This was the reason for the threshold in the name. But we now just use one
threshold per accelerating voltage determined empirically. So, I think this
is ok to remove from the name.
