### ISSUE TITLE
Add indication that scan is in progress

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#282]
Watch for data file creation, when a file appears create scan and use indeterminate progress indicator to indicate that the scan is in progress.

**Comment by cjh1** [comment]
We might need to introduce a more explicit scan state.

**Comment by ercius** [comment]
this is being worked on with a JSON output file from the 4D Camera receivers. WIP

**Comment by ercius** [comment]
JSON status files make this unnecessary. This can be closed.
