### ISSUE TITLE
Job failed due to copy

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#368]
I received this error after running job ID 1640 for distiller ID:
"cp: cannot create regular file '/global/cfs/projectdirs/ncemhub/distiller/counted/2022.04.25/data_scan274_id1926_electrons.h5': Permission denied"

This is due to the existence of a file with the same name that was counted on mothership6 locally. The file was copied from that machine to the `ncemhub/distiller/counted/2022.04.25` directory.

There is no need to account for this rare occurrence. I just wanted to mention this in case this error might happen when counting the same data set twice through Distiller.

**Comment by cjh1** [comment]
@ercius I think this might also be resolved by a collab account/group.

**Comment by ercius** [comment]
Ill look into that!
