### ISSUE TITLE
add row-dark option

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#502]
We should add an option to the "Count job" parameter window and script to use normal, row-dark mean, row-dark median.
![image](https://user-images.githubusercontent.com/15657108/190213749-51633d62-180b-4665-b78a-70395ac683de.png)

**Comment by alesgenova** [comment]
What should the name of the new field be?

**Comment by cjh1** [comment]
Algorithm?

**Comment by ercius** [comment]
Or maybe a check box since this the row-dark is applied before the
algorithm?

**Comment by cjh1** [comment]
@ercius So a checkbox to enable row-dark and then a drop down for mean or median? What was the "normal" you mentioned above ( no row dark subtraction? )

**Comment by ercius** [comment]
This will be nice to get integrated!

**Comment by ercius** [comment]
@cjh1 Can we implement this? The row-dark option is useful to clean up the patterns for many users.

**Comment by cjh1** [comment]
I believe this is close. I think @alesgenova just needs to finish testing it.
