### ISSUE TITLE
space left

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#522]
We need a way for the user to tell how much space is left on the mothership 6 drives. Maybe add this to the front page in the upper right. We just need to look at the % remaining in `/mnt/nvmedata5` right now.

**Comment by cjh1** [comment]
What would be the longest refresh interval that would be useful. As in we need to run a command on ms6 to get the information and probably don't want to run it every second!

**Comment by ercius** [comment]
How about every time something changed: a new scan is acquired or a scan is deleted? If that is harder than it sounds then maybe once every 1-5 minutes (Im not sure what would be considered too often). There also could be a button for the user to run it manually.

**Comment by cjh1** [comment]
Good idea, we can come up with something that doesn't trash too much ...

**Comment by cjh1** [comment]
Fixed in #620
