### ISSUE TITLE
add ability to redirect to a templated jupyter notebook

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#590]

**Comment by Tribhuvan0** [comment]
Hi, I want to work on this issue can you please assign this to me and tell me how should I proceed further

**Comment by arijitde92** [comment]
Hi, I am interested in solving this issue. Could you please add a description of the issue and guide me on how to proceed?

**Comment by cjh1** [comment]
This issue is actually already fixed, closing it.
