### ISSUE TITLE
Progress is complete even when a receiver is down

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#667]
The 4D Camera has 4 receivers which offload data and thus create 4 json progress files. If one of the receivers is down then only 3 json files will be created. In this case, if the 3 json files show 100% offload then Distiller reports the data set is complete. It seems like Distiller looks at the available json files and reports complete if all json files are 100%. This is undesirable because the data is not actually complete.

We need to change this logic to always look for 4 json files or report complete only when reaching 100% complete offload for 4 receivers. The logic for reporting scan offload completion could be changed to `sum(json_complete) / 400` instead of `sum(json_complete) / num_json_files`. Im not sure where the current logic is, but Im assuming its something like the latter.

**Comment by cjh1** [comment]
So my impression from our discussion of the new progress files that the progress recorded in each file was the global progress, just duplicated across the files  ( I don't have the email chain to check 😦 ). Based on that we just use the progress from any of the files to determine completeness. You are saying its the progress for each of the receivers?

**Comment by ercius** [comment]
> You are saying its the progress for each of the receivers?

Yes. Each receiver is completely independent. So, we need to add up all 4 percents. Its also possible for the percent to be > 100 if we acquire multiple frame per probe position. Im not sure if that number is in the JSON file.

Here is an example of 2 frames per position:
```json
{
   "UUID" : "78f4ee83-1950-46af-afe0-80c432a7e800",
   "disable_log_files" : false,
   "images_captured" : 525092,
   "images_written" : 525092,
   "last_scan_npositions" : 262656,
   "last_scan_number" : 24,
   "nreceiving_threads" : 18,
   "progress" : 199.9162402534113,
   "time" : "Fri, 06 Jan 23 00:19:28 +0000"
}
```
It would probably be best to have `nframes_per_position` in this file or have the percent calculated properly.

You can see many JSON files at this location which I just took off the system:
`ncemhub/4Dcamera/json_examples`

**Comment by cjh1** [comment]
OK, we can make the necessary changes, but as you say we will need either `nframes_per_position` or the percentage to be calculated using this.

**Comment by ercius** [comment]
I have asked the software maintainer to make that change. Ill send example files when I have them

**Comment by ercius** [comment]
One of the issues here has been resolved. The JSON file now outputs the `percent complete` from 0 - 100% always. This is only the percent complete for **each** receiver separately.

We do need to read all 4 json files and divide the sum of the `percent complete` by 4 to get the actual total

**Comment by cjh1** [comment]
Excellent, I will look at making the necessary change on our end.

**Comment by ercius** [comment]
@cjh1 This is not working correctly. The scan is immediately marked as finished. Im not sure if this is on our end (i.e. the JSON is not updating correctly) or on your end.

**Comment by ercius** [comment]
I can confirm that the JSON offload progress indicates percentage offloaded correctly.

During offload:
```
{
   "UUID" : "4a3334c5-bd1e-4f03-8f8f-4c42acd14514",
   "disable_log_files" : true,
   "images_captured" : 137949,
   "images_written" : 137949,
   "last_scan_npositions" : 262656,
   "last_scan_number" : 54,
   "n_frames_per_position" : 1,
   "nreceiving_threads" : 18,
   "progress" : 52.520787646198833,
   "time" : "Mon, 18 Mar 24 21:44:09 +0000"
}
```

Offload complete:
```
{
   "UUID" : "4a3334c5-bd1e-4f03-8f8f-4c42acd14514",
   "disable_log_files" : true,
   "images_captured" : 262601,
   "images_written" : 262601,
   "last_scan_npositions" : 262656,
   "last_scan_number" : 54,
   "n_frames_per_position" : 1,
   "nreceiving_threads" : 18,
   "progress" : 99.979060063352833,
   "time" : "Mon, 18 Mar 24 21:44:09 +0000"
}
```

Distiller shows this immediately:
![image](https://github.com/OpenChemistry/distiller/assets/15657108/02c41119-6e2f-4927-b7fa-32126f7f4867)
