### ISSUE TITLE
Add  some metadata about the scan size and shape

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#67]
Read from one of the data files.

**Comment by cjh1** [comment]
Also include metadata from the DM4 file, here is any [example](https://github.com/ercius/Xi-cam.NCEM/blob/dff760ddf31f4d09109f42b386f3699aa046ea18/xicam/NCEM/ingestors/DMPlugin.py#L47) of extracting the data. This would be displayed in and advanced section.

**Comment by cjh1** [comment]
@ercius Can we rely on extracting the scan size from the DM4?

**Comment by ercius** [comment]
Almost. The actual size of the sparse data will have one extra column for
the fly back. You could just add 1 to the column value in the DM4.

**Comment by cjh1** [comment]
We will use the scan size from the DM4 ( without the fly back )

**Comment by cjh1** [comment]
Fixed in #313, now deployed.
