### ISSUE TITLE
DM4s to ncemhub

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#71]
The DM4 files should be saved on ncemhub where the raw and counted data is. Probably in a dated directory (like the raw data) in a parent direction called dm4

**Comment by cjh1** [comment]
I think we can just add code to [haadf_worker](https://github.com/OpenChemistry/distiller/blob/main/backend/faust/haadf_worker.py) to do this. We will have to mount the global file system into it container on spin.

**Comment by cjh1** [comment]
@ercius So it is pretty simple just to copy over the files that appear in the samba share. Should we also deal with the situation where the detector has been reset? If that is the case the logic will be we a little more complicated, we can add in the distiller id into the file name.

**Comment by ercius** [comment]
@cjh1 Simple copy and overwrite it ok. The user saves them locally as well. We will be able to remove the scan number reset when the detector resets.

**Comment by cjh1** [comment]
Fixed by #109
