### ISSUE TITLE
Counted data in dated directory

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#72]
Scan numbering is currently not guaranteed to be unique. We should put counted data in a dated folder like the raw data.

Possibly also include the the Distiller scan ID in the file name in case of a scan number reset in the same day. This would happen if the detector needed to be restarted for example.

**Comment by ercius** [comment]
Does this use the date it was counted or the date the raw data was acquired?

**Comment by cjh1** [comment]
When the scan was created ( raw data )

**Comment by cjh1** [comment]
Now deployed
