### ISSUE TITLE
Add separate endpoint to fetch jobs for a scan

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#73]
The jobs and there output can get little large ... so `GET /scans` endpoint is starting to have fetch lot of data ...

**Comment by cjh1** [comment]
Add pagination of scans will resolve this with out need to change the jobs endpoints ... Fixes by: #94

**Comment by ercius** [comment]
We currently only see 100 scans in Distiller. The Edit field has important information. Will we be able to see older scans and data with this update? i.e. separate pages of 100 scans.

**Comment by cjh1** [comment]
Yes, they will just be paginated. So you will be able to load them in batches.

**Comment by cjh1** [comment]
Now deployed
