### ISSUE TITLE
Change Launch Jupyter Notebook to Perlmutter

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#764]
Jupyter notebooks are opened using a Cori Shared server. Cori will be retired soon and we should switch to using Perlmutter.

**Comment by ercius** [comment]
Cori will be retired at the end of the month.

**Comment by cjh1** [comment]
So we just redirect to: `https://jupyter.nersc.gov/hub/user-redirect/lab/tree` which then redirects to cori. So I am guessing that this will be update when cori is switched off, but will confirm. It shouldn't require a code change here.

**Comment by cjh1** [comment]
I can confirm this will be changed on the `jupyter.nersc.gov` side, no changes needed here.
