### ISSUE TITLE
Export and filter dates dont match

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#870]
If you set the filter to start on 09/01/23 and end on 09/05/23 then all data between [09/01/23 to 09/05/23) will be shown where the end date is not included. However, if you then press "export" the JSON file will include the end day. The export should follow what is shown in the webpage (i.e. not the end date).

**Comment by cjh1** [comment]
@ercius I think the confusion here is the timezone. As far as I can tell the same scans are being export, the screenshot below is the CSV export for 09/01/23 to 09/05/23 ( 13 scans ). 

<img width="584" alt="Screenshot 2023-10-03 at 10 46 44 AM" src="https://github.com/OpenChemistry/distiller/assets/1031053/84bdb584-1077-44d2-8745-2fb79e833d75">

The timezones for the created time in the browser are display in the local timezone ( including the start and end filter dates ). However, when we export the data the times are shown in UTC. Does that make sense? Are there changes we could make to improve this?

**Comment by ercius** [comment]
Darn those pesky time zones!

I think we need to make it so that what is shown on the webpage is what gets exported. Or we can make it more clear by requiring the user to select the scans to be exported using the check boxes.
![image](https://github.com/OpenChemistry/distiller/assets/15657108/8e3bc054-ffb2-4b5d-a49b-da542c06a728)

**Comment by cjh1** [comment]
So the scans that are shown on the webpage is what gets exported. The difference is that the `created` timestamp is exported as UTC.

**Comment by ercius** [comment]
Ok! I get it now. You are correct. There is nothing to fix!
