### ISSUE TITLE
scan thumbnail on the scan page doesn't preserve aspect ratio

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/distiller#956]

**Comment by cjh1** [comment]
@ercius Currently we don't preserve the aspect ratio, we use the "cover" option that will crop the image if necessary. I think preserving the aspect ratio might be a better option, which would be switching to the "contain" option. Examples of the CSS options can be found here: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit. Let us know what you think.

**Comment by ercius** [comment]
Preserving aspect ratio is preferred. So the contain option is best.
