### ISSUE TITLE
Deprecation warning in watch.py

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#970]
I found this warning in the logs:
`Jan 22 15:36:09 vfdaq python[20498]: /home/kitware/distiller/cli/watch/distiller/watch.py:173: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead`

**Comment by ercius** [comment]
This line does not exist anymore in the online repo. I guess vfdaq's watch service is fairly old.

From vfdaq file ../distiller/cli/watch/distiller/watch.py:
```
172     try:
173         async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False)) as session:
174             while True:
175                 async for event in AIOEventIterator(queue):
176                     if isinstance(event, FileSystemEvent):
177                         path = AsyncPath(event.src_path)
```

**Comment by cjh1** [comment]
@ercius I think this was a local change made to fix an issue we had with ssl certs, when there is some downtime I can try reverting the change.

**Comment by cjh1** [comment]
This was indeed a local change. vfdaq is now up to date.
